# Generated by Django 4.2.6 on 2024-02-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.BigIntegerField()),
                ('count', models.IntegerField()),
                ('price_for_week', models.IntegerField(blank=True, null=True)),
                ('price_for_sale', models.IntegerField(blank=True, null=True)),
                ('book_state', models.CharField(choices=[('new', 'Новая'), ('used', 'Б/У'), ('damaged', 'Поврежденная')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('in_rent', 'В аренде'), ('reserved', 'В резерве'), ('sold', 'Продана')], max_length=15)),
                ('purpose', models.CharField(choices=[('rent', 'В аренду'), ('sale', 'На продажу'), ('rent and sale', 'В аренду и на продажу')], max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.BigIntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='images/book_pics/blank.jpg', null=True, upload_to='images/book_pics', verbose_name='Фото книг')),
                ('book_shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='rents.usershelf', verbose_name='Объявление пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOfRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_plan_start', models.DateField(blank=True, null=True)),
                ('date_plan_end', models.DateField(blank=True, null=True)),
                ('date_fact_start', models.DateField(blank=True, null=True)),
                ('date_fact_end', models.DateField(blank=True, null=True)),
                ('number_for_owner', models.IntegerField(blank=True, null=True)),
                ('number_for_renter', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True)),
                ('purpose', models.CharField(choices=[('rent', 'Арендовать'), ('buy', 'Купить')], default='rent', max_length=10)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usershelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.usershelf')),
            ],
        ),
    ]
